server:
  port: 8888
  servlet:
    context-path: /

# jpa config
spring:
  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: